name: AutoUpdatePlugins
main: com.github.weikkadd.pddss.Main
version: 1.0.0
api-version: 1.18
description: Automatically update Spigot/Paper/Folia/BungeeCord/Velocity plugins
author: weikkadd
url: https://github.com/weikkadd/pddss
softdepend: [Vault, PlaceholderAPI]

commands:
  update:
    description: Update all plugins from list.yml
    usage: /update
    permission: autoupdateplugins.update
    aliases: [autoupdate, au]
  aup:
    description: Manage AutoUpdatePlugins
    usage: /aup
    permission: autoupdateplugins.manage
    aliases: [autoupdatesettings, aus]

permissions:
  autoupdateplugins.update:
    description: Allows updating plugins
    default: op
  autoupdateplugins.manage:
    description: Allows managing plugin list
    default: op
  autoupdateplugins.notify:
    description: Receive update notifications
    default: true
