name: AutoUpdatePlugins
main: spigot.SpigotUpdate
version: 12.2.0
api-version: 1.18
description: 自动更新 Spigot/Paper/Folia/BungeeCord/Velocity 插件
author: NewAmazingPVP
url: https://github.com/NewAmazingPVP/AutoUpdatePlugins
softdepend: [Vault, PlaceholderAPI]

commands:
  update:
    description: 从 list.yml 更新所有插件
    usage: /update
    permission: autoupdateplugins.update
    aliases: [autoupdate, au]
  aup:
    description: 管理 AutoUpdatePlugins
    usage: /aup
    permission: autoupdateplugins.manage
    aliases: [autoupdatesettings, aus]

permissions:
  autoupdateplugins.update:
    description: 允许更新插件
    default: op
  autoupdateplugins.manage:
    description: 允许管理插件列表
    default: op
  autoupdateplugins.notify:
    description: 接收更新通知
    default: true
